import { Book, SubscriptionPlan } from './types';

export const BOOKS: Book[] = [
  {
    id: '1',
    title: 'The Cosmic Frontier',
    author: 'Dr. Stella Nova',
    price: 59.90,
    discountPrice: 45.00,
    cover: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=800',
    category: 'Sci-Fi',
    description: 'A journey through the deepest reaches of the galaxy, exploring the mysteries of dark matter and ancient civilizations.',
    rating: 4.8,
    reviews: 124,
    stock: 5,
  },
  {
    id: '2',
    title: 'Malaysian Heritage: A Visual Journey',
    author: 'Ahmad Zaki',
    price: 85.00,
    cover: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800',
    category: 'History',
    description: 'Explore the rich cultural tapestry and architectural wonders of Malaysia through stunning photography and deep historical insights.',
    rating: 4.9,
    reviews: 89,
    stock: 12,
  },
  {
    id: '3',
    title: 'Quantum Leadership',
    author: 'Sarah Chen',
    price: 49.00,
    discountPrice: 39.00,
    cover: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=800',
    category: 'Business',
    description: 'Applying the principles of quantum physics to modern management and leadership in a rapidly changing world.',
    rating: 4.7,
    reviews: 210,
    stock: 3,
  },
  {
    id: '4',
    title: 'The Silent Nebula',
    author: 'Marcus Vane',
    price: 35.00,
    cover: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800',
    category: 'Fiction',
    description: 'A gripping tale of space exploration and the silence that follows a catastrophic event on a distant moon.',
    rating: 4.5,
    reviews: 56,
    stock: 20,
  },
  {
    id: '5',
    title: 'Batik Dreams',
    author: 'Siti Aminah',
    price: 42.00,
    cover: 'https://images.unsplash.com/photo-1535905557558-afc4877a26fc?auto=format&fit=crop&q=80&w=800',
    category: 'Art',
    description: 'The intricate world of Malaysian Batik, its history, techniques, and the dreams woven into every pattern.',
    rating: 4.8,
    reviews: 45,
    stock: 8,
  },
  {
    id: '6',
    title: 'The Starry Night Guide',
    author: 'Vincent Van G.',
    price: 0,
    cover: 'https://images.unsplash.com/photo-1506318137071-a8e063b4b477?auto=format&fit=crop&q=80&w=800',
    category: 'Science',
    description: 'A beginner\'s guide to stargazing and understanding the constellations in the night sky.',
    rating: 4.6,
    reviews: 340,
    stock: 100,
    isFree: true,
    isDigital: true,
  },
  {
    id: '7',
    title: 'Malaysian Street Food Secrets',
    author: 'Chef Wan',
    price: 0,
    cover: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800',
    category: 'Cooking',
    description: 'Discover the hidden gems and secret recipes of Malaysia\'s world-famous street food culture.',
    rating: 4.9,
    reviews: 520,
    stock: 100,
    isFree: true,
    isDigital: true,
  }
];

export const PLANS: SubscriptionPlan[] = [
  {
    id: 'basic',
    name: 'Basic Reader',
    price: 19.90,
    features: ['1 Free Ebook per month', '10% Discount on physical books', 'Access to community forum'],
  },
  {
    id: 'pro',
    name: 'Pro Explorer',
    price: 39.90,
    features: ['3 Free Ebooks per month', '20% Discount on physical books', 'Early access to new releases', 'Free shipping in Malaysia'],
    isPopular: true,
  },
  {
    id: 'cosmic',
    name: 'Cosmic Elite 🌌',
    price: 79.90,
    features: ['Unlimited Ebooks', '30% Discount on physical books', '1 Signed physical book per month', 'Exclusive author webinars', 'VIP support'],
  }
];
